server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/candidate_db
    username: postgres
    password: Hiccup@23
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate: 
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
